services:
  - type: web
    name: sudimartin-be
    runtime: node
    plan: free
    rootDir: be
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
